model:
  class_path: VQMultiModel
  init_args:
    ddconfig:
      double_z: false
      ch: 128
      num_res_blocks: 2
      dropout: 0.0
    lossconfig:
      disc_conditional: false
      disc_in_channels: 3
      disc_start: 7000
      disc_weight: 0.5
      codebook_weight: 0.5
    n_embed: 4096
    embed_dim: 8

data:
  class_path: CIFAR10DataModule
  init_args:
    batch_size: 256
    num_workers: 8

trainer:
  callbacks:
    - class_path: lightning.pytorch.callbacks.ModelCheckpoint
      init_args:
        save_top_k: -1
        every_n_epochs: 1
        save_last: true
        dirpath: /home/ubuntu/cifar-testing/ndp/cifar10/model
    - class_path: lightning.pytorch.callbacks.LearningRateMonitor
      init_args:
        logging_interval: step
  default_root_dir: ${working_dir}
  max_epochs: 50
  precision: bf16-mixed
  devices: 1
  log_every_n_steps: 10
  accelerator: cuda

seed_everything: 23
