model:
  class_path: DifficultyViT
  init_args:
    vocab_size: 16585
    resolutions: [1, 2, 4, 8, 16]
    hidden_dim: 512
    depth: 1
    heads: 8
    mlp_dim: 1024
    dim_head: 128
data:
  class_path: cli_diffvit.TinyImageNetDataModule
  init_args:
    batch_size: 8
    num_workers: 8

trainer:
  callbacks:
    - class_path: lightning.pytorch.callbacks.ModelCheckpoint
      init_args:
        save_top_k: -1
        every_n_epochs: 1
        save_last: true
        dirpath: ./tinyimagenet/diffvit
    - class_path: lightning.pytorch.callbacks.LearningRateMonitor
      init_args:
        logging_interval: step
  default_root_dir: ${working_dir}
  max_epochs: 50
  precision: bf16-mixed
  devices: 1
  log_every_n_steps: 10
  accelerator: mps

seed_everything: 23
