model:
  class_path: VQMultiModel
  init_args:
    ddconfig:
      double_z: false
      ch: 128
      num_res_blocks: 2
      dropout: 0.0
    lossconfig:
      disc_conditional: false
      disc_in_channels: 3
      disc_start: 201000
      disc_weight: 0.2
      perceptual_weight: 1.0
      codebook_weight: 1.0
    n_embed: 4096
    embed_dim: 8
    token_drop: [32, 8, 2, 0]
data:
  class_path: cli_multi.ImageNetDataModule
  init_args:
    batch_size: 8
    num_workers: 32

trainer:
  callbacks:
    - class_path: lightning.pytorch.callbacks.ModelCheckpoint
      init_args:
        save_top_k: -1
        every_n_epochs: 2
        save_last: false
        dirpath: /mnt/ndp/imagenet_256/vqgan_32768_16
    - class_path: lightning.pytorch.callbacks.LearningRateMonitor
      init_args:
        logging_interval: step
  default_root_dir: ${working_dir}
  strategy:
    class_path: lightning.pytorch.strategies.DDPStrategy
    init_args:
      find_unused_parameters: true
  max_epochs: 50
  precision: bf16-mixed
  devices: 8
  num_nodes: 4
  log_every_n_steps: 10
  accelerator: cuda

seed_everything: 23
