model:
  class_path: models.vit.NDPViT
  init_args:
    vocab_size: 5120
    resolutions: [1, 2, 4, 8, 16]
    hidden_dim: 768
    depth: 12
    heads: 12
    mlp_dim: 1536
    dim_head: 64
data:
  class_path: cli_diffvit.ImageNetDataModule
  init_args:
    batch_size: 128
    num_workers: 8

trainer:
  callbacks:
    - class_path: lightning.pytorch.callbacks.ModelCheckpoint
      init_args:
        save_top_k: -1
        every_n_epochs: 5
        save_last: true
        dirpath: ./imagenet/ndpvit
    - class_path: lightning.pytorch.callbacks.LearningRateMonitor
      init_args:
        logging_interval: step
  default_root_dir: ${working_dir}
  max_epochs: 200
  strategy:
    class_path: lightning.pytorch.strategies.DDPStrategy
    init_args:
      find_unused_parameters: true
  precision: bf16-mixed
  devices: 8
  log_every_n_steps: 10
  accelerator: cuda

seed_everything: 23
