model:
  class_path: models.vit.NDPViT
  init_args:
    vocab_size: 32832
    resolutions: [1, 2, 4, 8, 16]
    hidden_dim: 1024
    depth: 16
    heads: 16
    mlp_dim: 2048
    dim_head: 64
data:
  class_path: cli_ndpvit.ImageNetDataModule
  init_args:
    batch_size: 64
    num_workers: 128

trainer:
  callbacks:
    - class_path: lightning.pytorch.callbacks.ModelCheckpoint
      init_args:
        save_top_k: -1
        every_n_epochs: 10
        save_last: false
        dirpath: ./imagenet_256/ndpvit_b
    - class_path: lightning.pytorch.callbacks.LearningRateMonitor
      init_args:
        logging_interval: step
  default_root_dir: ${working_dir}
  max_epochs: 300
  strategy: ddp
  precision: bf16-mixed
  check_val_every_n_epoch: 5
  gradient_clip_val: 1.0
  devices: 8
  log_every_n_steps: 10
  accelerator: cuda

seed_everything: 23
